### ISSUE TITLE
feature request: config: hypereconomy: false

### ISSUE THREAD

**Issue by njdro** [Nutty101/DynmapNPCs#1]
Please add a config option to disable hypereconomy checking so i dont get this error in my logs:
`[Server thread/ERROR]: [DynMapNPC] Hyperconomoy Not found`
thank you

**Comment by Nutty101** [comment]
OOPS! gimme a few

**Comment by Nutty101** [comment]
I changed the log level for you to information. That should avoid the error in the logs. Sorry about that.
