### ISSUE TITLE
work on 1.12.2 ?

### ISSUE THREAD

**Issue by titanium63** [Nutty101/DynmapNPCs#2]
Hello,
I haven't error on console but i can't show npc in dynmap.
markerShowOnMap is on true and i have add trait dynmapnpc.
Have i miss somethings ?

**Comment by Nutty101** [comment]
It should work. I need to fire up a server with Dynmap and see.   Could you give me your versions of Dynmap, Citizens, and MC build? Will try to replicate that and see what happens.

**Comment by titanium63** [comment]
version MC : spigot-1.12.2-R0.1-SNAPSHOT-b1480
version Dynmap : dynmap-3.0-SNAPSHOT
version Citizen : citizens-2.0.22-SNAPSHOT

**Comment by titanium63** [comment]
Have you any idea for this issue ?

**Comment by Nutty101** [comment]
I so spaced this, sorry. I will try to make sure i get this setup and tested in the next day or so. If I don't respond, please ping me again to remind me.

**Comment by titanium63** [comment]
Have you test this setup ?

**Comment by Nutty101** [comment]
Yeah, it works. The icon set was not working for me, but thats cause i deleted a config. So the NPC's show up and move around, etc.  

What issues are you having with it?  I am using Dynmap 2.5 to test it with.

**Comment by titanium63** [comment]
I have select my npc, run /trait dynmapnpc and customise. When i looking for /dmnpc npc, i have that : 
Icon : house
name : test
description : hello
min zoom : 10
max zoom : 1
visible : showing on dynmap
But in my dynmap, there are nothings

I am using Dynmap 3.0 and Minecraft 1.12.2

**Comment by titanium63** [comment]
I have open test server for try with only 3 plugins (Dynmap 2.5, Citizens 2.0.22 and DynMapNPCs 1.4 with Mincecrat 1.12.2 or 1.11 ) but i don't understand, how do you make for show npc on dynmap.
Can you tell me step by step ?

**Comment by Nutty101** [comment]
if you zoom in and out to all levels 1-10 do they show on one or the other?  Also try reversing the zoom setting on them 1 and 10, and 10 and 1. See if that makes any difference.

**Comment by titanium63** [comment]
Thank you very much ! The default config file is reverse (minzoom: 10, maxzoom:1) but I should have thought to look at the zoom ... 
Again thank you

**Comment by Nutty101** [comment]
Ahh, I will look into fixing that default config. My bad, thanks for letting me know about that.
